events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;

    log_format main '$time_iso8601 | $status | ${request_time}s | $remote_addr | $request';
    access_log /var/log/nginx/access.log main;

    server {
        listen 80;

        # Default response
        location / {
            default_type application/json;
            return 404 '{"error":"environment not found","hint":"POST /api/envs to create one"}';
        }

        # Per-environment routes included from conf.d/
        include /etc/nginx/conf.d/*.conf;
    }
}